Update version and bug fixes

diff --git a/src/bin/osgit-selfupdate b/src/bin/osgit-selfupdate
--- a/src/bin/osgit-selfupdate
+++ b/src/bin/osgit-selfupdate
@@ -1,20 +1,28 @@
 #!/bin/sh
 
-if "$(id -u)" != 0; then
+set -eu
+
+if test "$(id -u)" != 0; then
   echo "This script must be run as root"
+  exit 1
 fi
 
-remote_version="$(curl https://raw.githubusercontent.com/cristianrz/osgit/master/VERSION | sed 's/.//g')"
+remote_version="$(curl -s https://raw.githubusercontent.com/cristianrz/osgit/master/VERSION)"
+if test -z "$remote_version"; then
+  echo 'could not find remote version'
+  exit 1
+fi
+
 echo "Remote version is $remote_version"
-local_version="$(osgit -v | sed 's/.//g; s/osgit//g')"
+local_version="$(osgit -v | sed 's/osgit//g')"
 echo "Local version is $local_version"
 
-if test "$remote_version" = "$local_version"; then
-  echo "You are on the latest version"
-  exit
-elif test "$remote_version" -lt "$local_version"; then
-  echo "You must be smarter than the average bear..."
-  exit
+printf "Do you want to update? [y/N] "
+read -r response
+
+if test "$response" != "y"; then
+  echo "aborted by the user"
+  exit 1
 fi
 
 tmp="$(mktemp -d)"
