Asd

diff --git a/usr/bin/osgit b/usr/bin/osgit
--- a/usr/bin/osgit
+++ b/usr/bin/osgit
@@ -7,8 +7,9 @@
 set -u
 
 export VERSION="0.5.0"
+PREFIX="$(cd "$(dirname "$0")"/.. || exit; pwd)"
 OSGITPATH="$PREFIX"/var/cache/osgit
-PREFIX="$(cd "$(dirname "$0")" || exit; pwd)"/..
+ORIGIN="$(pwd)"
 
 # shellcheck source=../lib/osgit/apt.sh
 . "$PREFIX"/lib/osgit/apt.sh
@@ -17,54 +18,70 @@ PREFIX="$(cd "$(dirname "$0")" || exit; pwd)"/..
 # shellcheck source=../lib/osgit/log.sh
 . "$PREFIX"/lib/osgit/log.sh
 
-__cleanup() {
-  test -z "$TMP" && log_fatal "TMP is not set"
 
-  if test -d "$TMP"; then
-    rm -f "$TMP"/* ||
-      log_fatal "no write access to tmp folder, bad previous cleanup?"
+__check_root(){
+  if test "$(id -u)" != 0; then
+    log_fatal "this command must be executed as root"
   fi
-}
-
-__startup() {
-  cd "$OSGITPATH" ||
-    log_fatal "Could not get into $OSGITPATH"
-
-  apt_get_installed >"$TMP"/packages.current
 }
 
 main() {
   args=
 
-  if test "$#" -eq 0 || test "$#" -lt 2 && test "$1" == "-d"; then
-    log_fatal "missing command"
-  elif test "$1" == "-d"; then
-    set -x && shift
+  if test "$#" -eq 0; then
+    log_fatal "$(commands_help "$VERSION")"
+  elif test "$#" -lt 2 && test "$1" = '-d' ; then
+    log_fatal "$(commands_help "$VERSION")"
+  elif test "$1" = "-d"; then
+    set -x
+    shift
   fi
 
-  subcommand="$1" && shift
+  subcommand="$1"
+  shift
 
-  test "$#" -gt 1 && args="$*"
+  if test "$#" -gt 0; then
+    args="$*"
+  fi
 
-  __startup
+  case "$subcommand" in
+    h* | v* | i*) ;;
+    *)
+      if ! cd "$OSGITPATH" 2> /dev/null; then
+        log_fatal "Could not cd into $OSGITPATH"
+      fi
+      ;;
+  esac
+
+  case "$subcommand" in
+    pi* | unp* | a* | c* | rev* | rm* | ro* | upd* | upgr* )
+      __check_root
+      git_make_this_master > /dev/null 2>&1
+      ;;
+  esac
+
+  case "$subcommand" in
+    pi* | un* | a* | c* | rev* | rm* | ro*)
+      if test "$#" -ne 1; then
+        log_fatal "incorrect number of arguments"
+      fi
+      ;;
+  esac
+
 
   # shellcheck disable=SC2086
   case "$subcommand" in
     a*) commands_add $args ;;
-    c*) commands_clone $args ;;
-    hi*) commands_log $args ;;
-    ini*) commands_init ;;
-    ins*) commands_add $args ;;
+    c*) commands_clone "$ORIGIN"/$args ;;
+    h*) log_fatal "$(commands_help "$VERSION")" ;;
+    i*) commands_init ;;
     li*) commands_list $args ;;
-    lo*) commands_log $args ;;
+    lo*) git log --oneline ;;
     pi*) commands_pin $args ;;
-    pu*) commands_rm $args ;;
-    rem*) commands_rm $args ;;
     rev*) commands_revert $args ;;
     rm) commands_rm $args ;;
     ro*) commands_rollback $args ;;
     s*) commands_show $args ;;
-    uni*) commands_rm $args ;;
     unp*) commands_unpin $args ;;
     upd*) commands_update $args ;;
     upg*) commands_upgrade $args ;;
@@ -72,7 +89,6 @@ main() {
     *) log_fatal "$(commands_help "$VERSION")" ;;
   esac
 
-  __cleanup
 }
 
 main "$@"
